#@ load("@ytt:data", "data")
---
apiVersion: v1
data:
  databasePassword: #@ data.values.data.databasePassword
  databaseUser: #@ data.values.data.databaseUser
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret

