apiVersion: v1
kind: Service
metadata:
  labels:
    app: toybank
  name: toybank
  namespace: test
spec:
  ports:
    - nodePort: 31000
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: toybank
  sessionAffinity: None
  type: NodePort
