#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: toybank
  name: toybank
  namespace: #@ data.values.metadata.namespace
spec:
  ports:
    - nodePort: #@ data.values.spec.ports.nodePort
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: toybank
  sessionAffinity: None
  type: NodePort
