apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: toybank-builder
  namespace: default
spec:
  serviceAccountName: kpack-service-account
  tag: pkatpivotal/image-builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java

